spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ums?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: passw
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: f16ad5da1640507c86b4
            clientSecret: 5affafecd317dcdb2520c93fdf4847f5e02f46ad
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8080

